import { z } from 'zod';

// ============================================================
// LLM Client Types – web-test-agent / src/llm/types.ts
// Data contracts and interfaces for LLM abstractions.
// ============================================================

export interface LLMMessage {
  role: 'user' | 'assistant' | 'system';
  content: string;
}

export interface LLMRequest {
  /** System prompt instruction */
  systemPrompt?: string;
  /** Primary user prompt */
  userPrompt: string;
  /** Target model name. Defaults to configured model */
  model?: string;
  /** Maximum tokens for completion */
  maxTokens?: number;
  /** Sampling temperature (0.0 = deterministic) */
  temperature?: number;
  /** Conversation message history if multi-turn */
  messages?: LLMMessage[];
}

export interface LLMUsage {
  inputTokens: number;
  outputTokens: number;
  totalTokens: number;
}

export interface LLMResponse {
  /** The text generated by the model */
  content: string;
  /** Model used for generation */
  model: string;
  /** Token usage statistics */
  usage: LLMUsage;
  /** Termination reason (e.g., 'end_turn', 'max_tokens', 'stop_sequence') */
  stopReason?: string;
}

export interface LLMClientConfig {
  /** Anthropic API Key. Defaults to process.env.ANTHROPIC_API_KEY */
  apiKey?: string;
  /** Default model. Defaults to 'claude-3-5-sonnet-20241022' */
  defaultModel?: string;
  /** Default max tokens. Defaults to 4096 */
  defaultMaxTokens?: number;
  /** Default temperature. Defaults to 0.0 */
  defaultTemperature?: number;
  /** Request timeout in milliseconds. Defaults to 60000 (60s) */
  timeoutMs?: number;
  /** Maximum retry attempts on transient network or 5xx/429 errors. Defaults to 2 */
  maxRetries?: number;
}

export interface LLMClient {
  /** Send completion request to LLM and return normalized response */
  complete(request: LLMRequest): Promise<LLMResponse>;
}

// ─── Error Classes ───────────────────────────────────────────

export class LLMError extends Error {
  readonly status?: number;
  readonly code?: string;

  constructor(message: string, status?: number, code?: string) {
    super(message);
    this.name = 'LLMError';
    this.status = status;
    this.code = code;
  }
}

export class APIKeyMissingError extends LLMError {
  constructor(message = 'ANTHROPIC_API_KEY is not set. Please set it in .env or pass it in config.') {
    super(message, undefined, 'API_KEY_MISSING');
    this.name = 'APIKeyMissingError';
  }
}

export class LLMTimeoutError extends LLMError {
  constructor(message = 'LLM request timed out.') {
    super(message, 408, 'TIMEOUT');
    this.name = 'LLMTimeoutError';
  }
}

export class RateLimitError extends LLMError {
  constructor(message = 'Anthropic API rate limit exceeded.') {
    super(message, 429, 'RATE_LIMIT');
    this.name = 'RateLimitError';
  }
}
